---
title: "rprojectplots"
author: "Nicholas Chen"
date: "2023-04-17"
output: html_document
---
```{r}
library(tidyverse)
library(ggmap)
url1 <- "https://raw.githubusercontent.com/CollinCoil/Programming-in-R-Project/main/Project_Data/BnB_data.csv?token=GHSAT0AAAAAACAZLVQWROLAJB2UFNPDPQWOZB5M3CQ"
bnb_data <- read.csv(url(url1))
bnb_data
```

Lets get some diagnostic data

Count of city
```{r}
bnb_data %>%
  count(City) %>%
  arrange(desc(n))


```
count of room type

```{r}
bnb_data %>%
  count(room_type) 
```

Count of time
```{r}
bnb_data %>%
  count(Time) %>%
  arrange(desc(n))
```
Count of city by time
```{r}
bnb_data %>%
  mutate(combine = paste(City, Time, sep = "_")) %>%
  count(combine) %>%
  arrange(desc(n))
```
Mean price bu city and time

```{r}
bnb_data %>%
  group_by(City, Time) %>%
  summarize(price = mean(realSum)) 
```

#plot 1: bar plot of price

```{r}
x <- bnb_data %>%
  group_by(City, Time) %>%
  summarize(price = mean(realSum)) %>%
  arrange(desc(price))

ggplot(data = x) +
  geom_bar(mapping = aes(x = reorder(City, price), y = price, fill = Time), stat = "identity", position=position_dodge()) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_text(aes(x = City, y = price, label = round(price), group = Time), 
            position = position_dodge(width = .9), vjust = -.2, size = 2, color ="black")+
  labs(title = "Mean price of AirBnb listings in European Cities", y = "Mean Price (Euros)", 
       x = "City") 
  

```
LETS MAP


```{r}
library(tidyverse)
library(ggmap)
library(maps)
library(mapdata)
```
find a good max for price gradient

```{r}
# outliers using Q3 + 1.5 IQR
amsterdam <- bnb_data %>%
  filter(City == "Amsterdam")

amsterdam_max <- quantile(amsterdam$realSum, prob = .75) + 1.5*(quantile(amsterdam$realSum, prob = .75) - quantile(amsterdam$realSum, prob = .25))
amsterdam_max



```

```{r}

load("~/Stat-412/Stat-412/amsterdamMap.RData")

#this gets values for a nice zoom
max_lng <- max(amsterdam$lng)
min_lng <- min(amsterdam$lng)
max_lat <- max(amsterdam$lat)
min_lat <- min(amsterdam$lat)

amsterdam_map<- ggmap(amsterdamMap) + 
  geom_point(data = filter(bnb_data, City == "Amsterdam"),
             mapping = aes(x=lng,y=lat, color = realSum), size = .9) +
  scale_colour_gradientn(
    colours=c('red','yellow','green'), 
    limits=c(0,amsterdam_max), 
    oob = scales::squish) +
  scale_x_continuous(limits = c(min_lng, max_lng), expand = c(0, 0)) +
  scale_y_continuous(limits = c(min_lat, max_lat), expand = c(0, 0)) +
  labs(title = "Mapping of AirBnB Listings in Amsterdam", y = "Latitude", 
       x = "Longitude", color = "Price") +
  theme(plot.title = element_text(size = 10)) 
amsterdam_map
```

lets loop our map data!!

```{r}
city_names <- c("Amsterdam", "Athens", "Barcelona", "Berlin", "Budapest", "Lisbon", "London", "Paris", "Rome", "Vienna")
myKey <- "AIzaSyB1iY3SlimxRoF4-KgIa8cI8aacBewvf2c"
register_google(key = myKey, account_type = "standard", day_limit = 100)

```

```{r}
for (name in city_names) {
  filtered <- bnb_data %>%
    filter(City == name)
  gradient_max <- quantile(filtered$realSum, prob = .75) + 1.5*(quantile(filtered$realSum, prob = .75) - quantile(filtered$realSum, prob = .25))
  max_lng <- max(filtered$lng)
  min_lng <- min(filtered$lng)
  max_lat <- max(filtered$lat)
  min_lat <- min(filtered$lat)
  map_lng <- (max_lng + min_lng)/2
  map_lat <- (max_lat + min_lat)/2
#gets maps by api key and then runs the amsterdam map code for all ten cities
  map<- ggmap(get_map(c(lon = map_lng, lat = map_lat), color = "bw", maptype = "roadmap")) + 
    geom_point(data = filter(bnb_data, City == name),
               mapping = aes(x=lng,y=lat, color = realSum), size = .9) +
    scale_colour_gradientn(
      colours=c('red','yellow','green'), 
      limits=c(0,gradient_max), 
      oob = scales::squish) +
    scale_x_continuous(limits = c(min_lng, max_lng), expand = c(0, 0)) +
    scale_y_continuous(limits = c(min_lat, max_lat), expand = c(0, 0)) +
    labs(title = paste("Mapping of AirBnB Listings in", name), y = "Latitude", 
         x = "Longitude", color = "Price") 
  map_name <- paste(name, "MapPrint", sep = "_")
  assign(map_name, map)
}

```
```{r}
Athens_MapPrint
```

```{r}
Budapest_MapPrint
```

```{r}
Barcelona_MapPrint
```
```{r}
Lisbon_MapPrint
```
```{r}
London_MapPrint
```
```{r}
Paris_MapPrint
```
```{r}
Rome_MapPrint
```
```{r}
Vienna_MapPrint
```
```{r}
Berlin_MapPrint
```

